/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrensaRouteImport } from './routes/prensa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosIndexRouteImport } from './routes/servicios.index'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos.index'
import { Route as ServiciosSlugRouteImport } from './routes/servicios.$slug'
import { Route as SectoresSlugRouteImport } from './routes/sectores.$slug'
import { Route as ProyectosSlugRouteImport } from './routes/proyectos.$slug'

const PrensaRoute = PrensaRouteImport.update({
  id: '/prensa',
  path: '/prensa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosIndexRoute = ServiciosIndexRouteImport.update({
  id: '/servicios/',
  path: '/servicios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSlugRoute = ServiciosSlugRouteImport.update({
  id: '/servicios/$slug',
  path: '/servicios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresSlugRoute = SectoresSlugRouteImport.update({
  id: '/sectores/$slug',
  path: '/sectores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosSlugRoute = ProyectosSlugRouteImport.update({
  id: '/proyectos/$slug',
  path: '/proyectos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prensa': typeof PrensaRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/sectores/$slug': typeof SectoresSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prensa': typeof PrensaRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/sectores/$slug': typeof SectoresSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/proyectos': typeof ProyectosIndexRoute
  '/servicios': typeof ServiciosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prensa': typeof PrensaRoute
  '/proyectos/$slug': typeof ProyectosSlugRoute
  '/sectores/$slug': typeof SectoresSlugRoute
  '/servicios/$slug': typeof ServiciosSlugRoute
  '/proyectos/': typeof ProyectosIndexRoute
  '/servicios/': typeof ServiciosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prensa'
    | '/proyectos/$slug'
    | '/sectores/$slug'
    | '/servicios/$slug'
    | '/proyectos/'
    | '/servicios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prensa'
    | '/proyectos/$slug'
    | '/sectores/$slug'
    | '/servicios/$slug'
    | '/proyectos'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/prensa'
    | '/proyectos/$slug'
    | '/sectores/$slug'
    | '/servicios/$slug'
    | '/proyectos/'
    | '/servicios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrensaRoute: typeof PrensaRoute
  ProyectosSlugRoute: typeof ProyectosSlugRoute
  SectoresSlugRoute: typeof SectoresSlugRoute
  ServiciosSlugRoute: typeof ServiciosSlugRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
  ServiciosIndexRoute: typeof ServiciosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prensa': {
      id: '/prensa'
      path: '/prensa'
      fullPath: '/prensa'
      preLoaderRoute: typeof PrensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/': {
      id: '/servicios/'
      path: '/servicios'
      fullPath: '/servicios/'
      preLoaderRoute: typeof ServiciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/$slug': {
      id: '/servicios/$slug'
      path: '/servicios/$slug'
      fullPath: '/servicios/$slug'
      preLoaderRoute: typeof ServiciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores/$slug': {
      id: '/sectores/$slug'
      path: '/sectores/$slug'
      fullPath: '/sectores/$slug'
      preLoaderRoute: typeof SectoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$slug': {
      id: '/proyectos/$slug'
      path: '/proyectos/$slug'
      fullPath: '/proyectos/$slug'
      preLoaderRoute: typeof ProyectosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrensaRoute: PrensaRoute,
  ProyectosSlugRoute: ProyectosSlugRoute,
  SectoresSlugRoute: SectoresSlugRoute,
  ServiciosSlugRoute: ServiciosSlugRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
  ServiciosIndexRoute: ServiciosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
